### ISSUE TITLE
Getting the logs logged incorrectly in report portal, while running parallel execution

### ISSUE THREAD

**Issue by metalimangal** [reportportal/logger-java-log4j#29]
Facing issue in parallel execution on report portal using the following versions
reportPortalAgentVersion=5.0.2
reportPortalLog4jVersion=5.0.1

Getting the failure error for one test case in another. Screenshots attached for the same here.

![Screenshot 2020-08-12 at 4 40 02 PM](https://user-images.githubusercontent.com/31962950/90241877-8c892b00-de49-11ea-8648-4dde915d61d1.png)
![Screenshot 2020-08-12 at 4 39 30 PM](https://user-images.githubusercontent.com/31962950/90241886-927f0c00-de49-11ea-8d46-b208037d0f8d.png)

**Comment by HardNorth** [comment]
Can you please provide an example project to reproduce?

**Comment by HardNorth** [comment]
Abandoned
