### ISSUE TITLE
Logs not reflecting in report portal after integrating with log4j2

### ISSUE THREAD

**Issue by rahulbhaviri** [reportportal/logger-java-log4j#31]
We have a testing framework (gauge) setup and we use slf4j with log4j for logging. Recently we implemented report portal for reporting purposes and it works as expected. It shows cases executed, passed, failed and failures cases has log shown inside them.

But I can't seem to configure logs to be shown at the launch level.

I followed this: "https://github.com/reportportal/logger-java-log4j" where I configured log4j2.xml file as shown but logs are not getting reflected in report portal. I'm able to print logs in console by changing the appender in log4j2.xml file though. So I'm guessing I'm doing something wrong with the setup.

This is the log4j2.xml file
`<?xml version="1.0" encoding="UTF-8"?>
<configuration packages="com.epam.ta.reportportal.log4j.appender">
    <properties>
        <property name="pattern">[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n</property>
    </properties>
    <appenders>
        <ReportPortalLog4j2Appender name="ReportPortalAppender">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
        </ReportPortalLog4j2Appender>
    </appenders>
    <loggers>
        <root level="debug">
            <appender-ref ref="ReportPortalAppender"/>
        </root>
    </loggers>
</configuration> `
I have added the following maven dependencies - **slf4j-api,logger-java-log4j,-slf4j-impl,log4j-api,log4j-core**

Let me know if I need to give more details for debugging.

**Comment by HardNorth** [comment]
@rahulbhaviri Are you using `ReportPortal.emitLaunchLog`?

**Comment by rahulbhaviri** [comment]
I'm aware there is a static function (ReportPortal.emitLaunchLog) but I'm not explicitly using it anywhere. I assumed if I configured log4j2.xml file with report portal appender it will be called inherently. Should I use it for log to reflect? if yes could you tell me how?

**Comment by HardNorth** [comment]
@rahulbhaviri it looks like I'm not getting your issue, can you share a screenshot what you mean?

**Comment by rahulbhaviri** [comment]
**I configured this (log4j2.xml)**
<img width="841" alt="Screenshot 2020-09-11 at 4 45 45 PM" src="https://user-images.githubusercontent.com/38429711/92919901-f4ce2b00-f44e-11ea-841c-691d9b3ecc82.png">
**this (pom.xml)**
<img width="755" alt="Screenshot 2020-09-11 at 4 46 11 PM" src="https://user-images.githubusercontent.com/38429711/92919906-f861b200-f44e-11ea-9d7d-49857c3ceab7.png">
**this (logger class)**
<img width="1096" alt="Screenshot 2020-09-11 at 4 46 50 PM" src="https://user-images.githubusercontent.com/38429711/92919921-fdbefc80-f44e-11ea-98ea-1a8dc4174557.png">
**yet this line (AUTOMATION_LOGGER.info) do not get reflected in report portal**
<img width="1052" alt="Screenshot 2020-09-11 at 4 47 12 PM" src="https://user-images.githubusercontent.com/38429711/92919927-01528380-f44f-11ea-9eef-ff599aa896aa.png">
**here**
<img width="1447" alt="Screenshot 2020-09-11 at 12 02 28 PM" src="https://user-images.githubusercontent.com/38429711/92920077-51314a80-f44f-11ea-9352-95a655b4497e.png">

**I want to know what else should be done configuration wise and code wise.**
Thank you.

**Comment by HardNorth** [comment]
@rahulbhaviri 
1. I don't see any point in `Automation logger` class. All these things can be done via logging pattern.
2. You are using too old, incompatible with the newest version of ReportPortal logger (version 3.0.0 was released something like 5 years ago). If you use  ReportPortal version 5, then please use logger version 5.0.3.

**Comment by rahulbhaviri** [comment]
Changed _logger-java-log4j_ version in pom.xml to 5.0.3; still no logs in log window.

**Comment by HardNorth** [comment]
@rahulbhaviri do you have any error or warnings in logs?

**Comment by rahulbhaviri** [comment]
Found this in logs:
2020-09-14 06:03:48,181 common.ReportUtil.main() ERROR Error processing element ReportPortalLog4j2Appender: CLASS_NOT_FOUND
[^[[1;34mINFO^[[m] /mindtickle-api-automation/src/test/java/api/base/BaseClient.java: Some input files use unchecked or unsafe operations.
[^[[1;34mINFO^[[m] ^[[1m------------------------------------------------------------------------^[[m
[^[[1;34mINFO^[[m]
2020-09-14 06:03:48,185 common.ReportUtil.main() ERROR Unable to locate plugin type for ReportPortalLog4j2Appender
[^[[1;34mINFO^[[m]

[^[[1;34mINFO^[[m] Total time:  16.853 s
[^[[1;34mINFO^[[m] ^[[1;32mBUILD SUCCESS^[[m
2020-09-14 06:03:48,224 common.ReportUtil.main() ERROR Unable to locate appender "ReportPortalAppender" for logger config "root"

**Comment by HardNorth** [comment]
@rahulbhaviri You have a dependency issue, looks like even on compile time. Can you use `-X` and provide the log? I mean something like: `mvn –X clean package`

**Comment by HardNorth** [comment]
@rahulbhaviri Regarding to your case it looks like your tests do not see your log4j xml configuration file. Therefore they are don't know about "packages" attribute and hence can't find `ReportPortalLog4j2Appender ` class. Please configure your test project properly.

Also minimum required version of log4j is: 2.12.1
