### ISSUE TITLE
Not able to log on report portal hosted over https . I am getting logs for passed tests but not for failed tests with stack trace 

### ISSUE THREAD

**Issue by samagarw** [reportportal/logger-java-log4j#43]
Not able to log on report portal hosted over https . I am getting logs for passed tests but not for failed tests with stack trace

**Comment by HardNorth** [comment]
There is no any limitations on HTTPS in Report Portal agents. Moreover Java makes it seamlessly and invisible for thier applications. So for HTTPS configuration please refer official Java documentation: https://docs.oracle.com/cd/E19148-01/819-4467/6n6k98bsb/index.html
