### ISSUE TITLE
Log4J Vulnerabilities in logger-java-log4j/5.1.5

### ISSUE THREAD

**Issue by qaautomationreqts** [reportportal/logger-java-log4j#47]
Please help with a new version having Vulnerabilities remediation from log4j:log4j@1.2.17.

At the moment, It has below 3 High and 2 Medium vulnerabilities as per Snyk Report and our organization security team is asking for it's remediation.
![image](https://user-images.githubusercontent.com/110539515/222434375-0cdb6162-ef9d-41c2-9f6c-9b28c328d36b.png)

**Comment by HardNorth** [comment]
@qaautomationreqts Just don't use Log4j 1.2

**Comment by qaautomationreqts** [comment]
@HardNorth  Issue is coming from below dependency only...
   <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.1.5</version>
        </dependency>

**Comment by HardNorth** [comment]
@qaautomationreqts Your scan just shows vulnerable dependency, yes, that's true, there are a lot of people who don't care and still use Log4j 1.2, therefor we support it. And to be true, I can't imagine an attack vector through automated tests, how would you do this? And the last one thing: If you don't use Log4j 1.2 you are safe, that's it.
