### ISSUE TITLE
Additional empty log files are created at default (root) directory instead of specific location

### ISSUE THREAD

**Issue by arunkumarkmj** [reportportal/logger-java-log4j#8]
I was using log4j (1.2.17) to log my test output to multiple files (Say A.log, B.log) to a specific location using RollingFileAppender which was behaving as expected like dumping separate logs in different files within specified location. Now after I started using ReportPortal with logger-java-log4j (4.0.1) , I am getting same files created in default location (root folder) as well but without any entries. Though rest of the things are working as expected like seeing old log files in specified location with all entries as well as ReportPortal Server shows required entries. Not sure why is this empty additional files created at root location. Can anyone help here. 

log4j.properties consists of following entries

```
log4j.rootLogger=INFO, A
log4j.logger.WEBUI=INFO, B

log4j.appender.A=org.apache.log4j.RollingFileAppender
log4j.appender.A.File=${my.log}A.log
log4j.appender.A.layout=org.apache.log4j.PatternLayout
log4j.appender.A.layout.ConversionPattern=%-7p %d %c %x - %m%n

log4j.appender.B=org.apache.log4j.RollingFileAppender
log4j.appender.B.File=${my.log}B.log
log4j.appender.B.layout=org.apache.log4j.PatternLayout
log4j.appender.B.layout.ConversionPattern=%-7p %d %c %x - %m%n

log4j.appender.reportportal=com.epam.ta.reportportal.log4j.appender.ReportPortalAppender
log4j.appender.reportportal.layout=org.apache.log4j.PatternLayout
log4j.appender.reportportal.layout.ConversionPattern=[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n
```

**Comment by arunkumarkmj** [comment]
Some additional data found on this..
After some debugging of logging behavior and ReportPortalTestNGListener code , it looks like logger is getting initialized through listener's static initialization even before my system variable (my.log) .

ReportPortalTestNGListener class is extended from BaseTestNGListener having following code..

```
public class BaseTestNGListener implements IExecutionListener, ISuiteListener, IResultListener2 {

	private static final Logger LOGGER = LoggerFactory.getLogger(BaseTestNGListener.class);
................
```

**Comment by DzmitryHumianiuk** [comment]
@arunkumarkmj did you manage to resolve it?

As i see, you can take control of logger initialization on you side.
But than you need to have own local customized version of `ReportPortalTestNGListener` and handle initialization of logger for it by yourself.

**Comment by filland** [comment]
@arunkumarkmj Hello, how do you  the set path to your log files ? 
Do you use log4j or slf4j's implementation for log4j ?

**Comment by filland** [comment]
@arunkumarkmj try this version https://github.com/reportportal/agent-java-testNG/tree/issue5-logger
I removed 'static' keywords for logger in BaseTestNGListener.
To use the version from my branch use this maven dependency:
```
<dependency>
     <groupId>com.github.reportportal</groupId>
     <artifactId>agent-java-testng</artifactId>
     <version>f5832da</version>
</dependency>
```

**Comment by arunkumarkmj** [comment]
Great.. thanks for all your inputs and help. 
As @DzmitryHumianiuk mentioned I thought of correcting it but it will be unnecessary maintenance of my own version ,so instead I preferred to clean it up through my framework after it gets created (for time being) . 
But with the given recent version of @filland this should be fixed now ,though I haven't tried it yet. Thanks!
