### ISSUE TITLE
CustomLevel log4j2

### ISSUE THREAD

**Issue by lilacharviv** [reportportal/logger-java-log4j#9]
Hello 
when i am using in log4j2 with CustomLevel
then i must to use level "debug" to see the results of the customlevel, but i dont want to print report portal all the results of debug, it makes the report of alot of junk that we want to print just for the log4j2 log
does have any other level that i can use with but also to see the result good.

**Comment by HardNorth** [comment]
@lilacharviv We do not support custom levels, this is a server limitation. Why don't you report on "info" level, it will have less logs?

**Comment by HardNorth** [comment]
abandoned
